/// @description Insert description here
// You can write your code in this editor
draw_self();

draw_text_color(x+40,y-26,jetpack,c_yellow,c_yellow,c_yellow,c_yellow,1);
draw_text_color(x+40,y-50,playhp,c_red,c_red,c_red,c_red,1);
draw_text_color(x-80,y-40,iron,c_orange,c_orange,c_orange,c_orange,1);

	ra = choose("Mario Speedwagon",
"Petey Cruiser",
"Anna Sthesia",
"Paul Molive",
"Anna Mull",
"Gail Forcewind",
"Paige Turner",
"Bob Frapples",
"Walter Melon",
"Nick R. Bocker",
"Barb Ackue",
"Buck Kinnear",
"Greta Life",
"Ira Membrit",
"Shonda Leer",
"Brock Lee",
"Maya Didas",
"Rick O'Shea",
"Pete Sariya",
"Monty Carlo",
"Sal Monella",
"Sue Vaneer",
"Cliff Hanger",
"Barb Dwyer",
"Terry Aki",
"Cory Ander",
"Robin Banks",
"Jimmy Changa",
"Barry Wine",
"Wilma Mumduya",
"Buster Hyman",
"Poppa Cherry",
"Zack Lee",
"Don Stairs",
"Saul T. Balls",
"Peter Pants",
"Hal Appeno",
"Otto Matic",
"Moe Fugga",
"Graham Cracker",
"Tom Foolery",
"Al Dente",
"Bud Wiser",
"Polly Tech",
"Holly Graham",
"Frank N. Stein",
"Cam L. Toe",
"Pat Agonia",
"Tara Zona",
"Barry Cade",
"Phil Anthropist",
"Marvin Gardens",
"Phil Harmonic",
"Arty Ficial",
"Will Power",
"Donatella Nobatti",
"Juan Annatoo",
"Stew Gots",
"Anna Rexia",
"Bill Emia",
"Curt N. Call",
"Max Emum",
"Minnie Mum",
"Bill Yerds",
"Hap E. Birthday",
"Matt Innae",
"Polly Science",
"Tara Misu",
"Ed U. Cation",
"Gerry Atric",
"Kerry Oaky",
"Midge Itz",
"Gabe Lackmen",
"Mary Christmas",
"Dan Druff",
"Jim Nasium",
"Angie O. Plasty",
"Ella Vator",
"Sal Vidge",
"Bart Ender",
"Artie Choke",
"Hans Olo",
"Marge Arin",
"Hugh Briss",
"Gene Poole",
"Ty Tanic",
"Manuel Labor",
"Lynn Guini",
"Claire Voyant",
"Peg Leg",
"Jack E. Sack",
"Marty Graw",
"Ash Wednesday",
"Olive Yu",
"Gene Jacket",
"Tom Atoe",
"Doug Out",
"Sharon Needles",
"Beau Tie",
"Serj Protector",
"Marcus Down",
"Warren Peace",
"Bud Jet",
"Barney Cull",
"Marion Gaze",
"Eric Shun",
"Mal Practice",
"Ed Itorial",
"Rick Shaw",
"Paul Issy",
"Ben Effit",
"Kat E. Gory",
"Justin Case",
"Louie Z. Ana",
"Aaron Ottix",
"Ty Ballgame",
"Anne Fibbiyon",
"Barry Cuda",
"John Withawind",
"Joe Thyme",
"Mary Goround",
"Marge Arita",
"Frank Senbeans",
"Bill Dabear",
"Ray Zindaroof",
"Adam Zapple",
"Lewis N. Clark",
"Matt Schtick",
"Sue Shee",
"Chris P. Bacon",
"Doug Lee Duckling",
"Mason Protesters",
"Sil Antro",
"Cal Orie",
"Sara Bellum",
"Al Acart",
"Marv Ellis",
"Evan Shlee",
"Terry Bull",
"Mort Ission",
"Mark Ette",
"Ken Tucky",
"Louis Ville","Colin Oscopy","Fred Attchini","Al Fredo");

	if dex>420 and dex <800 {
		draw_text_color(x-560,y-290,"Special Agent: ",c_yellow,c_yellow,c_yellow,c_yellow,1);
		draw_text_color(x-560,y-260,ra,c_yellow,c_yellow,c_yellow,c_yellow,1);
		draw_text_color(x-560,y-220,"Hold S - Use your rocket accelerator. Press 1-4 to toggle between weapons. The Desert Eagle (4) doesnt need iron to shoot. 5 to holster weapon.....",c_yellow,c_yellow,c_yellow,c_yellow,1);
		}
	if dex>800 and dex <1300 {
		draw_text_color(x-560,y-290,"Special Agent: ",c_yellow,c_yellow,c_yellow,c_yellow,1);
		draw_text_color(x-560,y-260,da,c_yellow,c_yellow,c_yellow,c_yellow,1);
		draw_text_color(x-560,y-220,"Hold S - Use your rocket accelerator",c_yellow,c_yellow,c_yellow,c_yellow,1);
		}

	if dex<420{
		draw_text_color(x-560,y-320,"Mission #1: Mine Iron Nodes and Reinforce your Space Station.\nA/D to move left and right.\nHold C to draw basic iron walls.\nShift to boost in direction.\nLeft Click to Shoot\nRight Click or F using an AK47 to fire GooWall Rounds\nSpacebar to Jump and Double jump\nPress and HOLD E To launch grappling hook *Tip:Pull rope down to Ascend or hold Spacebar when hooked.\nPress ESC to Quit\nPress R to Restart.\nZ to alternate fullscreen/windowed ",c_yellow,c_yellow,c_yellow,c_yellow,1);
		}

if instance_exists(o_grapple) and instance_exists(o_gpoint) and hook !=0 and grappled!=0 {draw_line_width_color(o_grapple.x,o_grapple.y,hook.x,hook.y,3,c_white,c_white);}